name: CI

on:
  push:
    paths:
    - 'epi_judge_java/epi/*.java'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.x' 
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64
    - name: run tests
      run: |
        set -x
        cd epi_judge_java
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep java | sed 's,epi_judge_java/epi/,,;s,.java,,' > files_to_test
        if [ -s files_to_test ]; then
            cat files_to_test | xargs make
        else
            echo "nothing to test"
            exit 0
        fi
