name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.x' 
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64
    - name: run tests
      run: |
        cd epi_judge_java
        git diff --name-only "$GITHUB_BASE_REF..$GITHUB_SHA" | sed 's,epi_judge_java/epi/,,;s,.java,,' | xargs make
